import { useEffect } from 'react';
import Head from 'next/head';
import { useQuery } from '@apollo/client';
import { GET_ANIME_LIST } from '@/services/animes';
import { ListAnime } from '@/components/organisms';

export default function Home() {
  const { loading, error, data } = useQuery(GET_ANIME_LIST, {
    variables: {
      page: 1,
      perPage: 10,
      search: null,
    },
  });

  useEffect(() => {
    console.log(loading, error, data);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [data]);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <div>
          <ListAnime
            data={data && data.Page?.media ? data.Page.media : []}
            isLoading={loading}
          />
        </div>
      </main>
    </>
  );
}
